export const LISTA_OBSERVADORES_AUTOMATICA = [
    { Agente: 'Susana Escalante', Estacion: 'Mercedez, Curuzú Cuatiá, Gob. Virasoro' },
    { Agente: 'Santiago Marciani', Estacion: 'Bariloche' },
    { Agente: 'Luciano Sánchez', Estacion: 'Viila Ana, La Cigüeña, Reconquista, Calchaquí, Cañada Ombú' },
    { Agente: 'Mariano Lestani', Estacion: 'Du Graty, Santa Sylvina, Basail, Colonia polpular, Las Breñas, Castelli, Presidencia La Plaza' },
    { Agente: 'Walter Opazo', Estacion: 'Gualjaina, Trevelin, Colan Conuhé' },
    { Agente: 'Jorge Rossi', Estacion: 'Junin, Santa Rosa' },
    { Agente: 'Ignacio Leiza', Estacion: 'Rauch, Las Armas' },
    { Agente: 'Claudio Giardina', Estacion: 'Rama Caída, La Guevarina' },
    { Agente: 'Eugenia Zeman', Estacion: 'Famailla, Trancas' },
    { Agente: 'Cristian Musi', Estacion: 'Valle Inferior, Guardia Mitre, General Conesa' },
    { Agente: 'Pablo Demin', Estacion: 'Sumalao, Andalgala' },
    { Agente: 'Gustavo Almada', Estacion: 'San Jorge' },
    { Agente: 'Mario Almirón', Estacion: 'Bella Vista, Goya, Esquina, Praje desmocada, Colonia Tabay' },
    { Agente: 'Martin Zarate', Estacion: 'Villa Dolores' },
    { Agente: 'Luis Fenoy', Estacion: 'Federal' },
    { Agente: 'Franco Rosso', Estacion: 'Corrientes, Caa Caty, Herlitzka, Ituzaingó' },
    { Agente: 'Laura Belmonte', Estacion: 'Anguil' },
    { Agente: 'Eduardo Ochner', Estacion: 'Santa Victoria Oeste, Abra Pampa, Hornillos' },
    { Agente: 'Gustavo Zura', Estacion: 'Medanos, Villa Longa, Stroeder' },
    { Agente: 'Ignacio Severina', Estacion: 'Manfredi' },
    { Agente: 'Sergio Godoy', Estacion: 'Villa Mercedes' },
    { Agente: 'Ignacio Huerga', Estacion: 'Hugues' },
    { Agente: 'Gustavo Maffini', Estacion: 'La Colmena, Maciá' },
    { Agente: 'Ángel Muñoz', Estacion: 'Gneral Roca, Rio Colorado' },
    { Agente: 'Claudio Lorenzón', Estacion: 'Marcos Juarez' },
    { Agente: 'Hugo Sicardi', Estacion: 'Andresito, Montecarlo, San Vicente, Cerro Azul, Posadas, Bernardo de Irigoyen' },
    { Agente: 'Gervasio Humano', Estacion: 'Los Antiguos, Perito Moreno, Jaramillo, Guer Aike, El Calafate, Esperanza, Gobernador Gregores.' },
    { Agente: 'German Guanca', Estacion: 'Palma Sola' },
    { Agente: 'Laura Mas', Estacion: 'Quimili, Sachayoj, Los Juries' },
    { Agente: 'Lucas Guillen', Estacion: 'Barreal' },
    { Agente: 'Gustavo Schumacher', Estacion: 'Bordenave' },
    { Agente: 'Marcelo Gersicich', Estacion: 'Dean Funes' },
    { Agente: 'Macarena Cardozo', Estacion: 'San Sebastian' },
    { Agente: 'Ricardo Centaure', Estacion: 'Junin' },
    { Agente: 'Javier Gonzales', Estacion: 'Puerto Piramides, Sarmiento, Paso de Indios' },
    { Agente: 'Omar Puig', Estacion: 'Bandera, Malbran' },
    { Agente: 'Verónica Sapino', Estacion: 'Rafaela' },
    { Agente: 'Nuria Lewczuk', Estacion: 'Balcarce' },
    { Agente: 'Nelson Dominguez', Estacion: 'Vaca Huañuna' },
    { Agente: 'Fidelina Silva ', Estacion: 'Monetcarlo' },
    { Agente: 'Franco Lazari', Estacion: 'Villa Ramallo, San Pedro, Rio Tala' },
    { Agente: 'Sonia Silva', Estacion: 'Pocito, Caucete' },
    { Agente: 'Gaston Moyano', Estacion: 'Tupungato, La Consulta, Pareditas' },
    { Agente: 'Cristina Millet', Estacion: 'Las Rosas' },
    { Agente: 'Marcos Anclao', Estacion: 'Paraje Golondrinas' },
    { Agente: 'Virginai Velazco', Estacion: 'Ing. Jacobacci' },
    { Agente: 'Edgar Flores', Estacion: 'Malargue' },
    { Agente: 'Victorio Dieta', Estacion: 'San Fernando' },
    { Agente: 'Gonzalo Arroquy', Estacion: 'Coronel Suarez, Casbas' },
    { Agente: 'Maria Jose Pizarro', Estacion: 'Torquinst' },
    { Agente: 'Maria Berriolo', Estacion: 'Loma Chata, Aparicio' },
    { Agente: 'Javiero Echague', Estacion: 'Lima' },
    { Agente: 'Fernando Ruiz', Estacion: '25 de Mayo' }


];